name: bitsdojo_window_macos_v3
description: macOS implementation of the bitsdojo_window plugin.
version: 3.0.0
homepage: https://www.bitsdojo.com
repository: https://github.com/DartGit-dev/bitsdojo_window

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface_v3:
    git:
      url: https://github.com/yalong0521/bitsdojo_window_platform_interface_v3.git
  ffi: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: BitsdojoWindowPlugin
